ARDUINO_DIR  = /usr/share/arduino
ARDMK_DIR     = /usr/share/arduino
AVR_TOOLS_DIR = /usr


ARDUINO_LIBS = Rainbowduino

BOARD_TAG    = atmega328
ARDUINO_PORT = /dev/ttyUSB1

include /usr/share/arduino/Arduino.mk

